require=(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({"./pages/index.js":[function(require,module,exports){
"use strict";var React=require("react/addons"),domReady=require("domready"),localStore=require("local-storage"),CommentList=require("../ui-component/comments/comment-list"),LoginForm=require("../ui-component/forms/login-form/form");domReady(function(){var e=JSON.parse(localStore.get("comments"));e&&(e=e.slice(0,3)),React.render(React.createElement(CommentList,{comments:e,title:"Last Comments"}),document.getElementById("comments")),React.render(React.createElement(LoginForm,null),document.getElementById("login-form"))});
},{"../ui-component/comments/comment-list":"C:\\work\\projects\\Misc\\react2\\js\\ui-component\\comments\\comment-list.js","../ui-component/forms/login-form/form":"C:\\work\\projects\\Misc\\react2\\js\\ui-component\\forms\\login-form\\form.js","domready":"C:\\work\\projects\\Misc\\react2\\js\\node_modules\\domready\\ready.js","local-storage":"C:\\work\\projects\\Misc\\react2\\js\\node_modules\\local-storage\\local-storage.js","react/addons":"C:\\work\\projects\\Misc\\react2\\js\\node_modules\\react\\addons.js"}],"C:\\work\\projects\\Misc\\react2\\js\\ui-component\\forms\\login-form\\form.js":[function(require,module,exports){
"use strict";var React=require("react/addons"),localStore=require("local-storage"),Email=require("../field-email/field"),Password=require("../field-password/field"),LoginForm=React.createClass({displayName:"LoginForm",getInitialState:function(){return{isValidEmail:!1,isValidPassword:!1}},onInputPassword:function(e){this.setState({isValidPassword:e})},onInputEmail:function(e){this.setState({isValidEmail:e})},storeEmail:function(){console.log(this.refs),localStore.set("email",this.refs.email.getDOMNode().value)},isValidForm:function(){return this.state.isValidPassword&&this.state.isValidEmail},render:function(){return React.createElement("div",null,React.createElement("form",{action:"/blog.html",method:"get",ref:"login-form",noValidate:!0,className:"login-form",onSubmit:this.storeEmail},React.createElement(Email,{ref:"email",onInput:this.onInputEmail}),React.createElement(Password,{ref:"password",onInput:this.onInputPassword}),React.createElement("p",null,React.createElement("input",{type:"submit",value:"Se connecter",disabled:!this.isValidForm()}))))}});module.exports=LoginForm;
},{"../field-email/field":"C:\\work\\projects\\Misc\\react2\\js\\ui-component\\forms\\field-email\\field.js","../field-password/field":"C:\\work\\projects\\Misc\\react2\\js\\ui-component\\forms\\field-password\\field.js","local-storage":"C:\\work\\projects\\Misc\\react2\\js\\node_modules\\local-storage\\local-storage.js","react/addons":"C:\\work\\projects\\Misc\\react2\\js\\node_modules\\react\\addons.js"}],"C:\\work\\projects\\Misc\\react2\\js\\ui-component\\forms\\field-password\\field.js":[function(require,module,exports){
"use strict";var React=require("react/addons"),notEmptyValidator=require("../validators/not-empty-validator"),Password=React.createClass({displayName:"Password",validate:function(a){this.props.onInput(notEmptyValidator(a.target.value))},render:function(){return React.createElement("input",{onChange:this.validate,placeholder:"Mot de passe...",ref:"password",type:"password",id:"password",name:"password",autoComplete:"off"})}});module.exports=Password;
},{"../validators/not-empty-validator":"C:\\work\\projects\\Misc\\react2\\js\\ui-component\\forms\\validators\\not-empty-validator.js","react/addons":"C:\\work\\projects\\Misc\\react2\\js\\node_modules\\react\\addons.js"}],"C:\\work\\projects\\Misc\\react2\\js\\ui-component\\forms\\field-email\\field.js":[function(require,module,exports){
"use strict";var React=require("react/addons"),notEmptyValidator=require("../validators/not-empty-validator"),emailValidator=require("../validators/email-validator"),Email=React.createClass({displayName:"Email",validate:function(a){this.props.onInput(notEmptyValidator(a.target.value)&&emailValidator.format(a.target.value))},render:function(){return React.createElement("input",{onChange:this.validate,ref:"email",type:"email",id:"email",name:"email",placeholder:"Adresse e-mail..."})}});module.exports=Email;
},{"../validators/email-validator":"C:\\work\\projects\\Misc\\react2\\js\\ui-component\\forms\\validators\\email-validator.js","../validators/not-empty-validator":"C:\\work\\projects\\Misc\\react2\\js\\ui-component\\forms\\validators\\not-empty-validator.js","react/addons":"C:\\work\\projects\\Misc\\react2\\js\\node_modules\\react\\addons.js"}],"C:\\work\\projects\\Misc\\react2\\js\\ui-component\\forms\\validators\\email-validator.js":[function(require,module,exports){
"use strict";module.exports={format:function(t){return/[^@]+@[^.]+\..+/.test(t)}};
},{}]},{},["./pages/index.js"]);
